version: "4.17"
services:
  mysql-farms:
    image: mysql:latest
    container_name: mysql-farms
    networks:
      - proxy
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongocontainer:
    container_name: mongocontainer
    image: mongo:latest
    networks:
      - proxy
    ports:
      - "27017:27017"


  user-auth-service:
    image: user-auth-service-image
    container_name: user-auth-service
    build: UserAuthentication/
    networks:
      - proxy
    ports:
      - "9002:9002"
    depends_on:
      - mysql-farms
      - api-gateway-service
      - eureka-service
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-container

  todolist-service:
    image: todolist-service-image
    container_name: todolist-service
    build: Todolist/
    networks:
      - proxy
    ports:
      - "9001:9001"
    depends_on:
      - mongocontainer
      - api-gateway-service
      - eureka-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-container


  notification-service:
    image: notification-service-image
    container_name: notification-service
    build: Notification-Service/
    networks:
      - proxy
    ports:
      - "9003:9003"
    depends_on:
      - mongocontainer
      - api-gateway-service
      - eureka-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-container



  api-gateway-service:
    image: api-gateway-service-image
    container_name: api-gateway-service
    build: Api-gateway/
    networks:
      - proxy
    ports:
      - "9500:9500"
    depends_on:
      - eureka-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-container

  eureka-service:
    image: eureka-image
    container_name: eureka-service
    build: Eureka-server/
    restart: always
    environment:
      EUREKA_SERVER_PORT: 8761
    networks:
      - proxy
    ports:
      - "8761:8761"


  rabbitmq-server:
    image: rabbitmq:3.10-management
    container_name: rabbitmq-container
    networks:
      - proxy
    ports:
      - "5672:5672"
      - "15672:15672"


networks:
  proxy:
    driver: bridge